version: "3.9"
services:
  create-snapshots:
    container_name: create-snapshots
    build:
      context: ../
      dockerfile: Dockerfile
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.11
    volumes:
      - ./protocol_parameters.json:/app/protocol_parameters.json:ro
      - ./snapshots:/app/snapshots
    command:
      - "tool"
      - "snap-gen"
      - "--protocolParametersPath=/app/protocol_parameters.json"
      - "--mintAddress=tst1qq2kvnu9pqzptkggrpqrvltvagccsh6aj2fkdhla7p3lrsy9dwhdzu5l2ye"
      - "--genesisAddresses=tst1qpszqzadsym6wpppd6z037dvlejmjuke7s24hm95s9fg9vpua7vlupxvxq2:1000000000000,tst1qqweu75ldpyann5jsthqsa6m0thx4tmqxncj6uqxf5q974pmqx30y5mcdp2:1000000000000"
      - "--outputPath=/app/snapshots/hornet-1b/full_snapshot.bin"
    profiles:
      - snapshots

  bootstrap-network:
    container_name: bootstrap-network
    build:
      context: ../
      dockerfile: Dockerfile
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.11
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    volumes:
      - ./config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./snapshots/hornet-1b:/app/snapshots
      - ./privatedb/hornet-1b:/app/privatedb
      - ./privatedb/state:/app/state
    command:
      - "tool"
      - "bootstrap-private-tangle"
      - "--configFile=/app/config_private_tangle.json"
      - "--snapshotPath=/app/snapshots/full_snapshot.bin"
      - "--databasePath=/app/privatedb"
      - "--cooStatePath=/app/state/coordinator.state"
    profiles:
      - bootstrap

  #
  # Nodes
  #
  hornet-1b:
    container_name: hornet-1b
    build:
      context: ../
      dockerfile: Dockerfile
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.11
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "15711:15600/tcp"
      - "14365:14265/tcp"
      - "9411:9311/tcp"
      - "9111:9029/tcp"
      - "6111:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./privatedb/hornet-1b:/app/privatedb
      - ./snapshots/hornet-1b:/app/snapshots
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=hornet-1b"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.212.11:9029"
      - "--p2p.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--p2p.peers=/ip4/172.18.212.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.212.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/172.18.212.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-2b,hornet-3b,hornet-4b"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.11:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.11:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  hornet-2b:
    container_name: hornet-2b
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.12
    depends_on:
      hornet-1b:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14366:14265/tcp"
      - "15712:15600/tcp"
      - "9412:9311/tcp"
      - "9112:9029/tcp"
      - "6112:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./privatedb/hornet-2b:/app/privatedb
      - ./snapshots/hornet-2b:/app/snapshots
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=hornet-2b"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.212.12:9029"
      - "--p2p.identityPrivateKey=a06b288ce7fc3b6f1e716f6f7d72050b53417aae4b305a68883550a3bb28597f254b082515a79391a7f13009b4133851a0c4d48e0e948809c3b46ff3e2500b4f"
      - "--p2p.peers=/ip4/172.18.212.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.212.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/172.18.212.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-1b,hornet-3b,hornet-4b"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.12:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.12:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  hornet-3b:
    container_name: hornet-3b
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.13
    depends_on:
      hornet-1b:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14367:14265/tcp"
      - "15713:15600/tcp"
      - "9413:9311/tcp"
      - "9113:9029/tcp"
      - "6113:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./privatedb/hornet-3b:/app/privatedb
      - ./snapshots/hornet-3b:/app/snapshots
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=hornet-3b"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.212.13:9029"
      - "--p2p.identityPrivateKey=5126767a84e1ced849dbbf2be809fd40f90bcfb81bd0d3309e2e25e34f803bf265500854f1f0e8fd3c389cf7b6b59cfd422b9319f257e2a8d3a772973560acdd"
      - "--p2p.peers=/ip4/172.18.212.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.212.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.212.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-1b,hornet-2b,hornet-4b"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.13:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.13:6060"
    profiles:
      - 3-nodes
      - 4-nodes

  hornet-4b:
    container_name: hornet-4b
    image: hornet:dev
    networks:
      peering_net:
        ipv4_address: 172.18.212.14
    depends_on:
      hornet-1b:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14368:14265/tcp"
      - "15714:15600/tcp"
      - "9414:9311/tcp"
      - "9114:9029/tcp"
      - "6114:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_private_tangle.json:/app/config_private_tangle.json:ro
      - ./privatedb/hornet-4b:/app/privatedb
      - ./snapshots/hornet-4b:/app/snapshots
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=hornet-4b"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.212.14:9029"
      - "--p2p.identityPrivateKey=996dceaeddcb5fc21480646f38ac53c4f5668fd33f3c0bfecfd004861d4a9dc722355dabd7f31a1266423abcf6c1db6228eb8283deb55731915ed06bd2ca387e"
      - "--p2p.peers=/ip4/172.18.212.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.212.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.212.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA"
      - "--p2p.peerAliases=hornet-1b,hornet-2b,hornet-3b"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.14:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.14:6060"
    profiles:
      - 4-nodes

  #
  # INX
  #
  inx-coordinator:
    container_name: inx-coordinator-b
    image: iotaledger/inx-coordinator:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.21
    depends_on:
      hornet-1b:
        condition: service_healthy
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    ports:
      - "6121:6060/tcp"
    volumes:
      - ./privatedb/state:/app/state
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--coordinator.stateFilePath=state/coordinator.state"
      - "--coordinator.blockBackups.enabled=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.21:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-indexer:
    container_name: inx-indexer-b
    image: iotaledger/inx-indexer:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.22
    depends_on:
      hornet-1b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9422:9311/tcp"
      - "6122:6060/tcp"
    volumes:
      - ./privatedb/indexer:/app/database
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--restAPI.bindAddress=172.18.212.22:9091"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.22:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.restAPIMetrics=true"
      - "--prometheus.inxMetrics=true"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.22:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-mqtt:
    container_name: inx-mqtt-b
    image: iotaledger/inx-mqtt:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.23
    depends_on:
      hornet-1b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9423:9311/tcp"
      - "6123:6060/tcp"
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--mqtt.websocket.bindAddress=172.18.212.23:1888"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.23:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.mqttMetrics=true"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.23:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-faucet:
    container_name: inx-faucet-b
    image: iotaledger/inx-faucet:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.24
    depends_on:
      hornet-1b:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    restart: on-failure
    ports:
      - "8191:8091/tcp"
      - "6124:6060/tcp"
    environment:
      - "FAUCET_PRV_KEY=887844b1e6bf9ca9e0b57584656add4370dbb49a8cb79e2e3032229f30fd80359e3df559ad0de8e5fa019b9ea46d1ee40879f3f3f74594a3306de9dfd43dcd25"
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--faucet.bindAddress=172.18.212.24:8091"
      - "--faucet.amount=100000000000"
      - "--faucet.smallAmount=10000000000"
      - "--faucet.maxAddressBalance=200000000000"
      - "--faucet.rateLimit.enabled=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.24:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-participation:
    container_name: inx-participation-b
    image: iotaledger/inx-participation:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.25
    depends_on:
      hornet-1b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9992:9892/tcp"
      - "6125:6060/tcp"
    volumes:
      - ./privatedb/participation:/app/database
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--restAPI.bindAddress=172.18.212.25:9892"
      - "--participation.db.path=/app/database"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.25:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-spammer:
    container_name: inx-spammer-b
    image: iotaledger/inx-spammer:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.26
    depends_on:
      hornet-1b:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    restart: on-failure
    ports:
      - "9426:9311/tcp"
      - "9192:9092/tcp"
      - "6126:6060/tcp"
    environment:
      - "SPAMMER_MNEMONIC=reward addict anger tongue denial supply cattle lawn foot climb ask friend base spring ensure spike alien equal burst bitter crowd august ignore animal"
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--restAPI.bindAddress=172.18.212.26:9092"
      - "--spammer.autostart=true"
      - "--spammer.bpsRateLimit=50"
      - "--spammer.cpuMaxUsage=0.0"
      - "--spammer.workers=0"
      - "--spammer.valueSpam.enabled=true"
      - "--spammer.valueSpam.sendBasicOutput=true"
      - "--spammer.valueSpam.collectBasicOutput=true"
      - "--spammer.valueSpam.createAlias=true"
      - "--spammer.valueSpam.destroyAlias=true"
      - "--spammer.valueSpam.createFoundry=true"
      - "--spammer.valueSpam.destroyFoundry=true"
      - "--spammer.valueSpam.mintNativeToken=true"
      - "--spammer.valueSpam.meltNativeToken=true"
      - "--spammer.valueSpam.createNFT=true"
      - "--spammer.valueSpam.destroyNFT=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.212.26:9311"
      - "--prometheus.spammerMetrics=true"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.26:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-poi:
    container_name: inx-poi-b
    image: iotaledger/inx-poi:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.27
    depends_on:
      hornet-1b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9787:9687/tcp"
      - "6127:6060/tcp"
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--restAPI.bindAddress=172.18.212.27:9687"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.27:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-dashboard-1:
    container_name: inx-dashboard-1b
    image: iotaledger/inx-dashboard:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.31
    depends_on:
      hornet-1b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9431:9311/tcp"
      - "8111:8081/tcp"
      - "6131:6060/tcp"
    command:
      - "--inx.address=172.18.212.11:9029"
      - "--dashboard.bindAddress=172.18.212.31:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.212.31:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.31:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-dashboard-2:
    container_name: inx-dashboard-2b
    image: iotaledger/inx-dashboard:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.32
    depends_on:
      hornet-2b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9432:9311/tcp"
      - "8112:8081/tcp"
      - "6132:6060/tcp"
    command:
      - "--inx.address=172.18.212.12:9029"
      - "--dashboard.bindAddress=172.18.212.32:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=a06b288ce7fc3b6f1e716f6f7d72050b53417aae4b305a68883550a3bb28597f254b082515a79391a7f13009b4133851a0c4d48e0e948809c3b46ff3e2500b4f"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.212.32:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.32:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes

  inx-dashboard-3:
    container_name: inx-dashboard-3b
    image: iotaledger/inx-dashboard:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.33
    depends_on:
      hornet-3b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9433:9311/tcp"
      - "8113:8081/tcp"
      - "6133:6060/tcp"
    command:
      - "--inx.address=172.18.212.13:9029"
      - "--dashboard.bindAddress=172.18.212.33:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=5126767a84e1ced849dbbf2be809fd40f90bcfb81bd0d3309e2e25e34f803bf265500854f1f0e8fd3c389cf7b6b59cfd422b9319f257e2a8d3a772973560acdd"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.212.33:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.33:6060"
    profiles:
      - 3-nodes
      - 4-nodes

  inx-dashboard-4:
    container_name: inx-dashboard-4b
    image: iotaledger/inx-dashboard:1.0
    networks:
      peering_net:
        ipv4_address: 172.18.212.34
    depends_on:
      hornet-4b:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9434:9311/tcp"
      - "8114:8081/tcp"
      - "6134:6060/tcp"
    command:
      - "--inx.address=172.18.212.14:9029"
      - "--dashboard.bindAddress=172.18.212.34:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=996dceaeddcb5fc21480646f38ac53c4f5668fd33f3c0bfecfd004861d4a9dc722355dabd7f31a1266423abcf6c1db6228eb8283deb55731915ed06bd2ca387e"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.212.34:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.212.34:6060"
    profiles:
      - 4-nodes

networks:
  peering_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.212.0/24"
